In [1]:
import os
import pandas as pd
import tensorflow as tf
from preprocess.data_utils import get_evalmask_token
from models.model_for_kt import TFTransfoXLMLMHeadModel

from transformers import TransfoXLConfig
os.environ["CUDA_VISIBLE_DEVICES"] = "1"


2024-01-25 12:05:27.852058: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-25 12:05:28.370596: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.4/lib64:
2024-01-25 12:05:28.370659: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.4/lib64:
2024-01-25 12:05:28.370664: W tensorflow/compiler/tf2tensorrt/utils/py_uti

In [2]:
config_xl = TransfoXLConfig.from_pretrained('/home/jun/workspace/KT/save_model/5ep_400mem_concepts.ckpt/config.json')



In [3]:
model = TFTransfoXLMLMHeadModel(config=config_xl)
model.load_weights('/home/jun/workspace/KT/save_model/5ep_400mem_concepts.ckpt/my_checkpoint')


2024-01-25 12:05:29.240902: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-01-25 12:05:29.245596: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-01-25 12:05:29.245910: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-01-25 12:05:29.246695: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorF

In [4]:

csv_file_path = '/home/jun/workspace/KT/data/ednet/test_mapping.csv' # 이 값을 사용자가 넣을 수 있도록 하자

df= pd.read_csv(csv_file_path)

In [5]:
df

is_repeat  \
0    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
1    0,0,0,0,0,1,1,1,0,0,0,0,0,1,1,1,0,1,1,1,1,0,1,...   
2    0,1,1,0,1,1,0,1,1,0,1,1,1,0,1,1,1,0,1,1,0,1,1,...   
3    0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,...   
4    0,1,1,0,1,1,0,1,1,0,1,1,1,0,1,1,1,0,1,1,0,1,1,...   
..                                                 ...   
993  0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,1,0,...   
994  0,0,0,1,1,1,0,0,0,0,0,1,1,1,1,0,1,1,1,1,0,1,1,...   
995  0,0,0,0,1,1,1,1,0,0,1,1,1,0,0,0,1,1,0,1,1,0,1,...   
996  0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,...   
997  0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,1,1,1,1,0,1,1,1,...   

                                            timestamps  \
0    1564025355829,1564025378419,1564025397966,1564...   
1    1549513111533,1549513145427,1549513181020,1549...   
2    1535168066809,1535168066809,1535168066809,1535...   
3    1563000044225,1563000093892,1563000093892,1563...   
4    1520702823096,1520702823096,1520702823096,1520...   
..                                                 ...   
993  1564009473995,1564009495228,1564009495228,1564...   
994  1562596663485,1562596680956,1562596701943,1562...   
995  1561381188298,1561381204728,1561381219781,1561...   
996  1562241328707,1562241367777,1562284666808,1562...   
997  1549745264982,1549745311960,1549745322728,1549...   

                                             responses  \
0    1,0,1,1,0,0,0,1,0,1,1,1,1,1,0,0,1,0,0,1,0,1,0,...   
1    1,1,0,1,1,1,1,1,1,0,1,0,0,0,0,0,1,1,1,1,1,1,1,...   
2    1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,...   
3    0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,...   
4    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,...   
..                                                 ...   
993  0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,0,...   
994  1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,0,0,0,0,0,1,1,1,...   
995  0,0,0,0,0,0,0,0,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,...   
996  0,0,1,1,1,1,0,0,1,0,0,1,1,0,1,1,0,1,1,0,1,1,1,...   
997  1,1,1,0,1,1,1,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,...   

                                              usetimes  \
0    27000,16000,16000,27000,69000,69000,40000,3600...   
1    19000,30000,32000,38000,23000,23000,23000,2300...   
2    23000,23000,23000,22000,22000,22000,26000,2600...   
3    34000,36000,36000,36000,36000,23000,19000,4600...   
4    31000,31000,31000,25000,25000,25000,26000,2600...   
..                                                 ...   
993  15000,15000,15000,15000,15000,15000,10000,1200...   
994  17000,12000,17000,17000,17000,17000,23000,4000...   
995  24000,10000,11000,22000,22000,22000,22000,2200...   
996  28000,33000,18000,18000,18000,18000,43000,3800...   
997  48000,43000,7000,40000,29000,18000,18000,18000...   

                                             questions  \
0    4860,6211,9250,4461,3240,3133,6966,9852,3535,6...   
1    5214,1254,4738,3263,116,116,116,116,328,2888,4...   
2    5330,5330,5330,3339,3339,3339,3381,3381,3381,8...   
3    4181,806,806,806,806,4245,683,173,6549,10264,1...   
4    5330,5330,5330,3339,3339,3339,3381,3381,3381,8...   
..                                                 ...   
993  3134,469,469,469,469,469,6902,9250,10642,9240,...   
994  4474,5556,112,112,112,112,7250,6966,4094,3275,...   
995  7246,1398,7007,5172,5172,5172,5172,5172,7810,6...   
996  682,7371,3744,3744,3744,3744,10727,10432,9509,...   
997  438,613,9,3467,7577,3855,3855,3855,3855,3468,6...   

                                              concepts   uid  
0    121,27,31,110,114,26,10,57,35,113,4,103,145,11...  3600  
1    91,139,25,108,6,92,47,43,87,101,108,25,99,129,...  2297  
2    44,41,9,162,46,49,155,46,49,6,130,9,47,30,77,4...  1910  
3    115,99,59,47,9,145,119,117,25,16,25,29,16,23,2...   681  
4    44,41,9,162,46,49,155,46,49,6,130,9,47,30,77,4...   189  
..                                                 ...   ...  
993  26,30,141,135,9,8,35,31,21,26,27,27,21,16,32,1...  4961  
994  19,114,6,90,49,47,26,10,10,124,88,6,60,47,9,54...  

In [6]:
question_list = df.loc[df['uid'] == 1910, 'questions']
concepts_list = df.loc[df['uid'] == 1910, 'concepts']
responses_list = df.loc[df['uid'] == 1910, 'responses']

In [7]:
question_list = [int(x) for x in question_list.values[0].split(',')]
concepts_list = [int(x) for x in concepts_list.values[0].split(',')]
responses_list = [int(x) for x in responses_list.values[0].split(',')]


In [8]:
masked_R, labels = get_evalmask_token(responses_list,config_xl.mask_token, config_xl.eos_token)


In [9]:
masked_R

<tf.Tensor: shape=(29335,), dtype=int32, numpy=array([1, 1, 1, ..., 3, 3, 3], dtype=int32)>

In [10]:



# 여기서 읽어온 데이터를 딕셔너리키 가지고 변환해서 ip mapping 하고 

# n_step = len(concepts_list) // (config_xl.tgt_len)

# sliced_qseqs = tf.slice(question_list,[0],[n_step *config_xl.tgt_len])  
# sliced_cseqs = tf.slice(concepts_list,[0],[n_step *config_xl.tgt_len])  
# sliced_masked_R = tf.slice(masked_R,[0],[n_step *config_xl.tgt_len]) 
# sliced_labels = tf.slice(labels,[0],[n_step *config_xl.tgt_len]) 


new_shape = (1, -1)  # 나머지 차원은 자동으로 계산됨

qseq_reshaped = tf.reshape(question_list, new_shape)
cseq_reshaped = tf.reshape(concepts_list, new_shape)
masked_R_reshaped = tf.reshape(masked_R, new_shape)
labels_reshaped = tf.reshape(labels, new_shape)


qseq_transposed = tf.transpose(qseq_reshaped)
cseq_transposed = tf.transpose(cseq_reshaped)
masked_R_transposed = tf.transpose(masked_R_reshaped)
labels_transposed = tf.transpose(labels_reshaped)

In [11]:
cseq_transposed

<tf.Tensor: shape=(29335, 1), dtype=int32, numpy=
array([[44],
       [41],
       [ 9],
       ...,
       [53],
       [49],
       [25]], dtype=int32)>

In [12]:
predict_dataset = tf.data.Dataset.from_tensor_slices(
    (cseq_transposed, masked_R_transposed,labels_transposed))

In [13]:
predict_dataset =predict_dataset.batch(config_xl.tgt_len, drop_remainder=False)

In [14]:
mems =None
predictions = []
for test_data1, test_data2, test_target in predict_dataset:
        outputs = model(concepts=test_data1, responses=test_data2, labels=test_target, mems=mems)
        loss = outputs.loss
        mems = outputs.mems
        
        reshape = tf.reshape(loss, [-1, config_xl.R_vocab_size])
        predicted_labels = tf.argmax(reshape, axis=1)
        predictions.append(predicted_labels.numpy().tolist())


In [15]:
flattened_list = [item for sublist in predictions for item in sublist]
flattened_list

[1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [17]:
df = pd.DataFrame({'Question':question_list,'Concepts':concepts_list,'Responses':flattened_list})

In [18]:
df.head(50)

Question  Concepts  Responses
0       5330        44          1
1       5330        41          1
2       5330         9          1
3       3339       162          0
4       3339        46          0
5       3339        49          0
6       3381       155          1
7       3381        46          1
8       3381        49          1
9        839         6          1
10       839       130          1
11       839         9          1
12       839        47          1
13      5333        30          1
14      5333        77          1
15      5333        49          1
16      5333        47          1
17      5331        77          1
18      5331        49          1
19      5331        47          1
20      5332        81          1
21      5332        49          1
22      5332        47          1
23      4299       164          1
24      4299        77          1
25      4299        47          1
26      4300       164          1
27      4300        53          1
28      4300        47          1
29      4298       164          1
30      4298        77          1
31      4298        47          1
32      5336        83          1
33      5336        77          1
34      5336        49          1
35      5335        83          1
36      5335        53          1
37      5335        49          1
38      5334        83          1
39      5334        77          1
40      5334        49          1
41      5339       164          1
42      5339        52          1
43      5339        43          1
44      5338       164          1
45      5338        51          1
46      5338        43          1
47      5337       164          1
48      5337        77          1
49      5337        43          1

In [ ]:
A = 5
B=2
print('this is {} {}'.format(A,B))

this is 5 2
